version: '3'

services:
  DB:
    image: mysql:5.7.40-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: teste
      MYSQL_USER: pablo
    ports:
      - 3306:3306