name: SSH Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client
        run: ls
      - name: install ssh
        run: apt install open-ssh
      - name: connect_ssh
        run: ssh -l teste localhost