name: SSH Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client
        run: ls
      - name: install ssh
        run: sudo apt-get install -y openssh-client sshpass
      - name: connect_ssh
        run: sshpass -p '${{ secrets.SSH_PASSWORD }}' ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "ls /"